# Generated by Django 4.1.7 on 2023-02-28 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('reward', models.IntegerField(default=0)),
                ('rewardType', models.CharField(choices=[('Coin', 'Coin'), ('Gem', 'Gem'), ('Card', 'Card')], default='Coin', max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('paymentType', models.CharField(choices=[('Rial', 'Money'), ('Ad', 'Ad')], default='Rial', max_length=10)),
                ('currency', models.CharField(choices=[('Dollar', 'Dollar'), ('Lira', 'Lira'), ('Rial', 'Rial')], default='Dollar', max_length=10)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('storeitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.storeitem')),
                ('username', models.CharField(max_length=50)),
            ],
            bases=('store.storeitem',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('userId', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('pricePaid', models.IntegerField(default=0)),
                ('adWatched', models.IntegerField(default=0)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('log', models.TextField(blank=True, default='')),
                ('receipts', models.ManyToManyField(blank=True, related_name='payment_receipts', to='store.receipt')),
            ],
        ),
    ]
