# Generated by Django 4.1.7 on 2023-02-28 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenegContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('target', models.IntegerField(default=0)),
                ('targetType', models.CharField(choices=[('Wins', 'Wins'), ('Fans', 'Fans'), ('Power', 'Power')], default='Wins', max_length=10)),
                ('reward', models.IntegerField(default=0)),
                ('rewardType', models.CharField(choices=[('Fan', 'Fan'), ('Coin', 'Coin'), ('Gem', 'Gem')], default='Fan', max_length=10)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('userId', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('nextIndex', models.IntegerField(default=0)),
                ('timestamp', models.IntegerField(default=0)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('log', models.TextField(blank=True, default='')),
                ('challenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailyChallenge.dailychallenegcontent')),
            ],
        ),
    ]
