# Generated by Django 4.1.7 on 2023-02-28 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('score', '0001_initial'),
        ('dailyChallenge', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('userId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('log', models.TextField(blank=True, default='')),
                ('dailyChallenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailyChallenge.dailychallenge')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.payment')),
                ('score', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='score.score')),
            ],
        ),
    ]
