# Generated by Django 4.1.7 on 2023-02-28 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('userId', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('coin', models.IntegerField(default=0)),
                ('gem', models.IntegerField(default=0)),
                ('cup', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('fan', models.IntegerField(default=0)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('log', models.TextField(blank=True, default='')),
            ],
        ),
    ]
