# Generated by Django 4.1.7 on 2023-02-28 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userId', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('emailAddress', models.EmailField(blank=True, max_length=254)),
                ('displayName', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=('male', 'Male'), max_length=10)),
                ('avatar', models.CharField(blank=True, max_length=50)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('log', models.TextField(blank=True, default='')),
            ],
        ),
    ]
